package org.mac.nasbackup.analyzer;

public enum Operation {

	CHECK_EXISTANCE_ON_TARGET_DEVICE, BUILD_REPORT, INSERT_NON_EXISTING_INTO_DB, INSERT_IF_NOT_EXISTS_ON_REFERENCE_DEVICE, INSERT_WITHOUT_EXISTANCE_CHECK;
	
}
